In [403]:
#importing libraries
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

#getting data into a dataframe
df = pd.read_csv("IOT_Assignment_2_data_regression_sensor_range.csv")
df.head(20)

Humidity(%)  Temperature(°C)  WaterFlow(%)
0     25.045045        76.856857     67.432607
1      8.880881        31.771772      0.000000
2     24.956957        75.735736     66.105904
3     40.328328        88.308308      0.000000
4     38.742743        57.157157      0.000000
5     45.613614        24.164164      0.000000
6     33.237237        43.383383      0.000000
7     23.415415        81.421421     73.999716
8     10.026026        96.316316    100.000000
9     15.399399        58.838839     50.670417
10    19.275275        38.338338     21.283602
11    16.016016        32.172172      0.000000
12     9.937938        66.046046     63.071230
13    42.310310        45.785786      0.000000
14    50.986987        46.986987      0.000000
15    29.581582        39.859860     17.185735
16    51.867868        50.350350      0.000000
17    19.231231        52.272272      0.000000
18    32.312312        49.709710      0.000000
19    40.064064        34.414414      0.000000

In [404]:
# To check wheather there are null values in the file or not
df.isnull().sum().sort_values(ascending=False)/df.shape[0]

Humidity(%)        0.0
Temperature(°C)    0.0
WaterFlow(%)       0.0
dtype: float64

In [405]:
#getting labels for water flow percentage and classifying zero and non zero values
y = list()
for i in range(0,len(df['WaterFlow(%)'])):
    if int(df['WaterFlow(%)'][i]) > 0:
        y.append([1])
    else:
        y.append([0])

X = data[data.columns[0:2]].values

train_x,test_x,train_y,test_y = train_test_split(X, y, random_state=42)


#using two layer mlp classifier to classify labels for zero(0) water flow and non zero water flow(1)
clf = MLPClassifier(hidden_layer_sizes = (2,2), activation = 'relu', learning_rate_init = 0.02, max_iter = 500, verbose = True).fit(X, y)
y_pred = clf.predict(test_x)


Iteration 1, loss = 5.94545442
Iteration 2, loss = 4.97490980
Iteration 3, loss = 4.09869556
Iteration 4, loss = 3.33549795
Iteration 5, loss = 2.66627763
Iteration 6, loss = 2.07807874
Iteration 7, loss = 1.61092384
Iteration 8, loss = 1.26247430
Iteration 9, loss = 1.02841577
Iteration 10, loss = 0.86581303
Iteration 11, loss = 0.74514625
Iteration 12, loss = 0.65421004
Iteration 13, loss = 0.57907961
Iteration 14, loss = 0.51830073
Iteration 15, loss = 0.47308316
Iteration 16, loss = 0.44640208
Iteration 17, loss = 0.44082724
Iteration 18, loss = 0.45549191
Iteration 19, loss = 0.48044951
Iteration 20, loss = 0.50168485
Iteration 21, loss = 0.51034811
Iteration 22, loss = 0.50537847
Iteration 23, loss = 0.49068219
Iteration 24, loss = 0.47191407
Iteration 25, loss = 0.45417125
Iteration 26, loss = 0.44124214
Iteration 27, loss = 0.43487000
Iteration 28, loss = 0.43452370
Iteration 29, loss = 0.43822815
Iteration 30, loss = 0.44332723
Iteration 31, loss = 0.44760105
Iteration 32, los

D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [406]:
#checking the accuracy of the model
accuracy_score(test_y, y_pred)


0.9

In [436]:
#getting the weights and the intercept to implement the model in the simulator
clf.coefs_, clf.intercepts_

([array([[-0.93719345, -0.14810805],
         [ 0.77089881, -0.00539169]]),
  array([[-0.31953528,  0.39291412],
         [ 0.12040542,  0.01305723]]),
  array([[0.8159931 ],
         [0.28688396]])],
 [array([-0.84375506,  0.16812373]),
  array([-1.28604286, -0.43244935]),
  array([-2.51558891])])

In [408]:
#getting the weigths and intercepts to use in the forward pass function
cw, cb = clf.coefs_,clf.intercepts_

#relu function to calculate the activations
def relu(n):
    return np.maximum(0,n)

#forward pass function to calculate the predictions. This funtion has been implemented in the simulator
def forward_pass(inputs):
    
    a = np.dot(relu(np.dot(relu(np.dot(np.array([inputs]), w[0]) +b[0]), w[1])+b[1]), w[2]) +b[2]
    if a > 1:
        return 1
    else:
        return int(0)
l1 = list()
for i in range(0, len(df['Humidity(%)'])):
    l1.append(forward_pass([df['Humidity(%)'][i], df['Temperature(°C)'][i]]))
print(l1)

#getting the accuracy score of the function predicted labels
accuracy_score(y, l1)

[1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]


0.81

In [414]:
#getting rows with non zero water flow percentage to fit a regression model
df1 = df.loc[df.iloc[:,2] > 0]
df1

Humidity(%)  Temperature(°C)  WaterFlow(%)
0      25.045045        76.856857     67.432607
2      24.956957        75.735736     66.105904
7      23.415415        81.421421     73.999716
8      10.026026        96.316316    100.000000
9      15.399399        58.838839     50.670417
..           ...              ...           ...
184    47.463463        93.673674     74.377179
187    17.117117        84.384384     81.384543
188    50.238238        88.388388     66.357958
190    11.435435        90.230230     91.859900
197    23.855856       100.000000     96.088487

[76 rows x 3 columns]

In [424]:
#Assign Humidity and Temperature values column to X and WaterFLow(%) to y
X = df1[df1.columns[0:2]].values
y = df1[df1.columns[2]]

train_x,test_x,train_y,test_y = train_test_split(X,y)

#using two layer mlp regressor to predict water flow percentage
mlp = MLPRegressor(hidden_layer_sizes = (2,2),max_iter = 2000, activation = "relu", learning_rate_init = 0.003, verbose = 1)
mlp.fit(X,y)

Iteration 1, loss = 1645.70270960
Iteration 2, loss = 1627.34412030
Iteration 3, loss = 1608.88560708
Iteration 4, loss = 1590.32812342
Iteration 5, loss = 1571.67272446
Iteration 6, loss = 1552.92057797
Iteration 7, loss = 1534.07297510
Iteration 8, loss = 1515.13134087
Iteration 9, loss = 1496.09724437
Iteration 10, loss = 1476.97240854
Iteration 11, loss = 1457.75871957
Iteration 12, loss = 1438.45823580
Iteration 13, loss = 1419.07319620
Iteration 14, loss = 1399.60602818
Iteration 15, loss = 1380.05935503
Iteration 16, loss = 1360.43600256
Iteration 17, loss = 1340.73900533
Iteration 18, loss = 1320.97161211
Iteration 19, loss = 1301.13729083
Iteration 20, loss = 1281.23973275
Iteration 21, loss = 1261.28285616
Iteration 22, loss = 1241.27080922
Iteration 23, loss = 1221.20797238
Iteration 24, loss = 1201.09895994
Iteration 25, loss = 1180.94862110
Iteration 26, loss = 1160.76204033
Iteration 27, loss = 1140.54453711
Iteration 28, loss = 1120.30166500
Iteration 29, loss = 1100.039

Iteration 314, loss = 26.71204850
Iteration 315, loss = 26.66617788
Iteration 316, loss = 26.62028828
Iteration 317, loss = 26.57438010
Iteration 318, loss = 26.52845371
Iteration 319, loss = 26.48250951
Iteration 320, loss = 26.43654787
Iteration 321, loss = 26.39056919
Iteration 322, loss = 26.34457383
Iteration 323, loss = 26.29856220
Iteration 324, loss = 26.25253466
Iteration 325, loss = 26.20649159
Iteration 326, loss = 26.16043339
Iteration 327, loss = 26.11436042
Iteration 328, loss = 26.06827307
Iteration 329, loss = 26.02217171
Iteration 330, loss = 25.97605673
Iteration 331, loss = 25.92992850
Iteration 332, loss = 25.88378739
Iteration 333, loss = 25.83763378
Iteration 334, loss = 25.79146805
Iteration 335, loss = 25.74529056
Iteration 336, loss = 25.69910171
Iteration 337, loss = 25.65290184
Iteration 338, loss = 25.60669135
Iteration 339, loss = 25.56047060
Iteration 340, loss = 25.51423996
Iteration 341, loss = 25.46799980
Iteration 342, loss = 25.42175049
Iteration 343,

Iteration 631, loss = 12.99591351
Iteration 632, loss = 12.96007135
Iteration 633, loss = 12.92429988
Iteration 634, loss = 12.88859928
Iteration 635, loss = 12.85296968
Iteration 636, loss = 12.81741124
Iteration 637, loss = 12.78192410
Iteration 638, loss = 12.74650842
Iteration 639, loss = 12.71116434
Iteration 640, loss = 12.67589200
Iteration 641, loss = 12.64069154
Iteration 642, loss = 12.60556312
Iteration 643, loss = 12.57050687
Iteration 644, loss = 12.53552293
Iteration 645, loss = 12.50061144
Iteration 646, loss = 12.46577254
Iteration 647, loss = 12.43100637
Iteration 648, loss = 12.39631306
Iteration 649, loss = 12.36169274
Iteration 650, loss = 12.32714556
Iteration 651, loss = 12.29267163
Iteration 652, loss = 12.25827110
Iteration 653, loss = 12.22394410
Iteration 654, loss = 12.18969075
Iteration 655, loss = 12.15551117
Iteration 656, loss = 12.12140551
Iteration 657, loss = 12.08737387
Iteration 658, loss = 12.05341639
Iteration 659, loss = 12.01953319
Iteration 660,

Iteration 977, loss = 2.84141016
Iteration 978, loss = 2.83774678
Iteration 979, loss = 2.83350797
Iteration 980, loss = 2.82960800
Iteration 981, loss = 2.82585163
Iteration 982, loss = 2.82179484
Iteration 983, loss = 2.81773485
Iteration 984, loss = 2.81413896
Iteration 985, loss = 2.80991201
Iteration 986, loss = 2.80584363
Iteration 987, loss = 2.80224532
Iteration 988, loss = 2.79781010
Iteration 989, loss = 2.79382025
Iteration 990, loss = 2.79009262
Iteration 991, loss = 2.78576222
Iteration 992, loss = 2.78227951
Iteration 993, loss = 2.77793558
Iteration 994, loss = 2.77386579
Iteration 995, loss = 2.76996116
Iteration 996, loss = 2.76546936
Iteration 997, loss = 2.76150590
Iteration 998, loss = 2.75732308
Iteration 999, loss = 2.75318606
Iteration 1000, loss = 2.74903968
Iteration 1001, loss = 2.74500355
Iteration 1002, loss = 2.74086009
Iteration 1003, loss = 2.73661547
Iteration 1004, loss = 2.73252912
Iteration 1005, loss = 2.72834873
Iteration 1006, loss = 2.72425310
Ite

Iteration 1290, loss = 1.35071771
Iteration 1291, loss = 1.34604623
Iteration 1292, loss = 1.34138134
Iteration 1293, loss = 1.33672309
Iteration 1294, loss = 1.33207151
Iteration 1295, loss = 1.32742665
Iteration 1296, loss = 1.32278857
Iteration 1297, loss = 1.31815728
Iteration 1298, loss = 1.31353286
Iteration 1299, loss = 1.30891532
Iteration 1300, loss = 1.30430473
Iteration 1301, loss = 1.29970112
Iteration 1302, loss = 1.29510453
Iteration 1303, loss = 1.29051500
Iteration 1304, loss = 1.28593259
Iteration 1305, loss = 1.28135733
Iteration 1306, loss = 1.27678928
Iteration 1307, loss = 1.27222849
Iteration 1308, loss = 1.26767508
Iteration 1309, loss = 1.26312917
Iteration 1310, loss = 1.25859110
Iteration 1311, loss = 1.25406149
Iteration 1312, loss = 1.24954201
Iteration 1313, loss = 1.24503657
Iteration 1314, loss = 1.24055544
Iteration 1315, loss = 1.23612510
Iteration 1316, loss = 1.23181474
Iteration 1317, loss = 1.22779398
Iteration 1318, loss = 1.22456813
Iteration 1319

Iteration 1609, loss = 0.32418021
Iteration 1610, loss = 0.32250497
Iteration 1611, loss = 0.32083261
Iteration 1612, loss = 0.31916893
Iteration 1613, loss = 0.31751811
Iteration 1614, loss = 0.31587521
Iteration 1615, loss = 0.31423707
Iteration 1616, loss = 0.31260770
Iteration 1617, loss = 0.31098952
Iteration 1618, loss = 0.30937929
Iteration 1619, loss = 0.30777498
Iteration 1620, loss = 0.30617904
Iteration 1621, loss = 0.30459319
Iteration 1622, loss = 0.30301557
Iteration 1623, loss = 0.30144458
Iteration 1624, loss = 0.29988151
Iteration 1625, loss = 0.29832774
Iteration 1626, loss = 0.29678241
Iteration 1627, loss = 0.29524424
Iteration 1628, loss = 0.29371365
Iteration 1629, loss = 0.29219169
Iteration 1630, loss = 0.29067823
Iteration 1631, loss = 0.28917236
Iteration 1632, loss = 0.28767392
Iteration 1633, loss = 0.28618355
Iteration 1634, loss = 0.28470152
Iteration 1635, loss = 0.28322738
Iteration 1636, loss = 0.28176073
Iteration 1637, loss = 0.28030174
Iteration 1638

Iteration 1922, loss = 0.08775547
Iteration 1923, loss = 0.08756163
Iteration 1924, loss = 0.08736947
Iteration 1925, loss = 0.08717898
Iteration 1926, loss = 0.08699015
Iteration 1927, loss = 0.08680296
Iteration 1928, loss = 0.08661741
Iteration 1929, loss = 0.08643348
Iteration 1930, loss = 0.08625116
Iteration 1931, loss = 0.08607043
Iteration 1932, loss = 0.08589129
Iteration 1933, loss = 0.08571373
Iteration 1934, loss = 0.08553772
Iteration 1935, loss = 0.08536327
Iteration 1936, loss = 0.08519035
Iteration 1937, loss = 0.08501896
Iteration 1938, loss = 0.08484909
Iteration 1939, loss = 0.08468072
Iteration 1940, loss = 0.08451385
Iteration 1941, loss = 0.08434847
Iteration 1942, loss = 0.08418457
Iteration 1943, loss = 0.08402214
Iteration 1944, loss = 0.08386120
Iteration 1945, loss = 0.08370177
Iteration 1946, loss = 0.08354387
Iteration 1947, loss = 0.08338759
Iteration 1948, loss = 0.08323308
Iteration 1949, loss = 0.08308065
Iteration 1950, loss = 0.08293084
Iteration 1951

D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=(2, 2), learning_rate_init=0.003, max_iter=2000,
             verbose=1)

In [425]:
pred = mlp.predict(test_x)
print(pred)

test_y = list(test_y)
print(test_y)

[89.35364263 73.73387177 65.75251503 61.21725611 34.44573319 28.87008418
 52.31462086 81.82096174 73.39966148 67.17971147 76.25513659 93.02475943
 82.31931666 78.75848273 69.61599166 78.26513148 65.75970178 61.77584787
 77.15030521]
[89.09714621590695, 73.99971561167865, 66.10590388555484, 61.58677797910583, 33.97902560001252, 27.96361988315612, 52.787370560052175, 81.82352242914317, 73.68309663467339, 67.40792954756792, 76.51493958528766, 92.78543541110464, 82.43728169955207, 78.7556633373631, 69.83109448021504, 78.16894411041427, 66.08493919279677, 62.09920645119234, 77.39556411322842]


In [426]:
#calculating rmse to check the difference between actual and predicted labels
mse = 0
for i in range(len(pred)):
    mse = mse + (pred[i]-test_y[i])*(pred[i]-test_y[i])
    
rmse = np.sqrt(mse)
print(rmse)
    

1.5026694067938662


In [437]:
#these are the weights and intercept used to calculate percentage water flow for values classified to be non zero
mlp.coefs_, mlp.intercepts_

([array([[ 0.14305889, -0.4585217 ],
         [-0.07857762,  1.43825024]]),
  array([[-3.14549834e+00,  7.47973997e-44],
         [ 1.35090029e+00, -9.27454579e-09]]),
  array([[5.66023597e-01],
         [1.58027859e-07]])],
 [array([ 6.40676167, -0.16284629]),
  array([-0.5421608, -1.1714177]),
  array([-1.18822247])])

In [433]:
#getting the weigths and intercepts to use in the forward pass function
rw, rb = mlp.coefs_,mlp.intercepts_

#relu function to calculate the activations
def relu(n):
    return np.maximum(0,n)

#forward pass function to calculate the predictions. This funtion has been implemented in the simulator for those values which
#are predicted to be non zero
def forward_pass(inputs):
    
    a = np.dot(relu(np.dot(relu(np.dot(np.array([inputs]), rw[0]) + rb[0]), rw[1]) + rb[1]), rw[2]) + rb[2]
    return a[0]

l = list()
h_list = list(df1['Humidity(%)'])
t_list = list(df1['Temperature(°C)'])
for i in range(0, len(df1['Humidity(%)'])):
    l.append(forward_pass([h_list[i], t_list[i]]))
print(l)


[array([67.08898926]), array([65.75251503]), array([73.73387177]), array([100.30302752]), array([50.59161083]), array([22.8321104]), array([62.83188649]), array([18.47974508]), array([32.63310181]), array([39.05059879]), array([73.39966148]), array([93.02475943]), array([43.05892994]), array([77.15030521]), array([75.33130805]), array([76.25513659]), array([86.63628933]), array([77.04266877]), array([29.19455769]), array([41.0836995]), array([99.42887805]), array([76.78298174]), array([22.13057664]), array([32.7349229]), array([90.95198698]), array([57.52193263]), array([53.02934951]), array([52.31462086]), array([72.59603606]), array([58.10127298]), array([88.01288932]), array([61.21725611]), array([63.10622689]), array([78.75848273]), array([46.97235619]), array([78.26513148]), array([80.40641906]), array([72.00531696]), array([59.9968894]), array([72.49767306]), array([59.76504131]), array([28.87008418]), array([82.31931666]), array([97.94627427]), array([74.355975]), array([65.7597

In [434]:
a = list(y)

mse = 0
for i in range(len(l)):
    mse = mse + (l[i] - a[i])**2
    
rmse = np.sqrt(mse)
print(rmse)

[3.41582875]


In [438]:
#Showing the matrices that are used in the simulator to implement Classification
print("Below are the weight and intercept matrices for the MLP Classifier")
clf.coefs_, clf.intercepts_

Below are the weight and intercept matrices for the MLP Classifier


([array([[-0.93719345, -0.14810805],
         [ 0.77089881, -0.00539169]]),
  array([[-0.31953528,  0.39291412],
         [ 0.12040542,  0.01305723]]),
  array([[0.8159931 ],
         [0.28688396]])],
 [array([-0.84375506,  0.16812373]),
  array([-1.28604286, -0.43244935]),
  array([-2.51558891])])

In [439]:
#Showing the matrices that are used in the simulator to implement Regression
print("Below are the weight and intercept matrices for the MLP Regressor")
mlp.coefs_, mlp.intercepts_

Below are the weight and intercept matrices for the MLP Regressor


([array([[ 0.14305889, -0.4585217 ],
         [-0.07857762,  1.43825024]]),
  array([[-3.14549834e+00,  7.47973997e-44],
         [ 1.35090029e+00, -9.27454579e-09]]),
  array([[5.66023597e-01],
         [1.58027859e-07]])],
 [array([ 6.40676167, -0.16284629]),
  array([-0.5421608, -1.1714177]),
  array([-1.18822247])])